name: Conditional Branch Protection Rule

on:
  workflow_dispatch:
    inputs:
      approver:
        description: 'GitHub username of the required approver (leave empty to disable rule)'
        required: false
        default: ''

jobs:
  update-branch-protection:
    runs-on: ubuntu-latest
    steps:
    - name: Set or Remove Branch Protection
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPROVER: ${{ github.event.inputs.approver }}
      run: |
        if [ -z "$APPROVER" ]; then
          # Disable the branch protection rule
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/branches/main/protection"
        else
          # Enable the branch protection rule with specific approver
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/branches/main/protection" \
          -d '{
                "required_pull_request_reviews": {
                  "required_approving_review_count": 1,
                  "require_code_owner_reviews": false,
                  "dismiss_stale_reviews": false,
                  "required_approving_review_count": 1,
                  "user_push_restrictions": ["'$APPROVER'"]
                },
                "enforce_admins": null,
                "required_status_checks": null,
                "restrictions": null
              }'
        fi
